title: Project Tracker
author: CyanCoding
email: skyecam21@gmail.com
theme: jekyll-theme-cayman
description: > # this means to ignore newlines until "baseurl:"
  Easily create, manage, track, and develop all of your programming projects.
# social links
github_username:  CyanCoding # DO NOT include the @ character, or else the build will fail!
show_downloads: true
show_excerpts: true # set to false to remove excerpts on the homepage
google_analytics: [UA-169049460-1]
